// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: find_user_name.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const findUserName = `-- name: FindUserName :one
SELECT name FROM users
WHERE id = $1
`

func (q *Queries) FindUserName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, findUserName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
